export const app_constant = {
  Community_Insights: 'communityinsight',
  Consider_This: ' considerthis',
  Course_Rating: ' courserating',
  Discussion_Question: 'discussionquestion',
  Expert_Insider: 'expertinsider',
  Expert_Question_Response: 'expertquestionresponse',
  Facilator: 'facilator',
  Glossary: 'glossary',
  Help_And_FAQs: 'helpandfaqs',
  Key_Takeaway: 'keytakeaway',
  Learning_Applied: 'learningapplied',
  News: 'news',
  POLL: 'poll',
  Pre_Activity: 'preactivity',
  Resource: 'resource',
  Review_Question: 'reviewquestion',
  Scenarios: 'scenarios',
  See: 'see',
  Upcoming_Training: 'upcomingtraining',
  Whats_Happening: 'whatshappening',
};
