export interface CoreData {
  UpcomingTrainingId: number,
// CourseEventId: number,
Title: string,
Description: string,
// TrainingFloId: number,
CourseImagePath: string,
StartDateTime: any,
EndDateTime: any,
CourseId:number
// WidgetId: number,
// WidgetTypeId: number,
// TrainingCommunityName:string,
// TrainingFloName: string,
// TrainingFloUrlName:string,
// CourseId: number,
LongDescription: string,
// TrainingFloDescription: any,
Facilitators:any[],
IsFacilitator: number,
// ConsultantId: 109,
FirstName: string,
LastName: string,
Email: any,
Designation:any,
// Description: any,
Bio: string,
ImageURL:string,
// VideoURL:string
}
